name: Unit test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit_test:
      runs-on: ubuntu-lastest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
  
      - name: Checkout Unit Test repository
        uses: actions/checkout@v4
        with:
          repository: RexAliis/TupleJsonConvertersUnitTest
          path: UnitTest
  
      - name: Run Unit Test
        run: dotnet test UnitTest/TupleJsonConvertersUnitTest/TupleJsonConvertersUnitTest.csproj
